# Sous le Rosier.
#

# Site settings
title: Sous le Rosier.
description: Sous le Rosier, chez la rêve... Mais je suis... de Froufrou à Fou...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lerosier.github.io" # the base hostname & protocol for your site
github_username:  lerosier
timezone: france/paris
# Build settings
markdown: kramdown
